runtime: python39
entrypoint: gunicorn -b :$PORT src.main:app --timeout 120

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  ENVIRONMENT: "production"
  GOOGLE_CLOUD_PROJECT: "pyusd-intent-system"
  GOOGLE_CLOUD_REGION: "us-central1"
  BIGQUERY_DATASET: pyusd_intent_system
  GCS_BUCKET: pyusd-intent-system-analytics

handlers:
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup 