/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iDexInterfacesSol from "./IDexInterfaces.sol";
export type { iDexInterfacesSol };
export type { IUniswapV2Factory } from "./IUniswapV2Factory";
export type { IUniswapV2Pair } from "./IUniswapV2Pair";
export type { IUniswapV2Router02 } from "./IUniswapV2Router02";
